### ISSUE TITLE
<#@ assembly name Directive File Locks Target DLL even after BIML File Closure

### ISSUE THREAD

**Issue by TravisKale** [varigence/BimlPit#111]
I'm submitting a...

[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => 
[ ] Other... Please describe:

Current Behavior:
When I use the assembly directive such as 
`<#@ assembly name = "..\YadaYadaYada\MyCustom.dll" #>`

The target dll becomes locked as soon as .biml file with that directive is opened.  The .dll remains locked even after the .biml file is closed, only way to remove file lock is to completetly shut down visual studio.   The process locking the file is Visual Studio devenv.exe.   

Expected Behavior

Assembly dll should not be file locked at all or at least release the file lock once the .biml file is closed.  I desire this behavior because restarting visual studio every time I want to modify/rebuild my custom dll is less than optimal.

Environment

BimlExpress version: 5.0.63773.0

Visual Studio Version:

- [ ] 2005
- [ ] 2008
- [ ] 2010
- [ ] 2012
- [ ] 2013
- [ ] 2015
- [x ] 2017

Target SSIS Version:

- [ ] 2005
- [ ] 2008
- [ ] 2008 R2
- [ ] 2012
- [ ] 2014
- [x ] 2016
- [x ] 2017

**Comment by jalley3** [comment]
We are aware of the issue, and unfortunately there is not much that we can do. The reason for this is that with .NET, it is literally impossible to unload a dll that has already been loaded into a process. The following microsoft article confirms as much: 

https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/assemblies-gac/how-to-load-and-unload-assemblies

The only way to architect this to avoid that issue is to create a separate app domain, then load up all of the dlls, and then after the program has finished running, destroy the separate app domain. Also, any communication between Visual Studio and the biml compiler would have to be through cross app domain communication channels which are both heavy and slow. We did try implementing this but during testing found it to be far too cumbersome and slow, to the point that it was not an acceptable approach for the large majority of our customers.

The number of users who implement their own custom dll's is relatively small, and unfortunately due to the way that .NET is designed, there is not anything that we can do to improve the user story. One work around, if your dll is relatively small, is to reference each code file in your dll via a code directive in your biml files, however if your dll is large, then this may be a non-starter. 

Sorry for any inconvenience that this may cause.

**Comment by TravisKale** [comment]
Thanks for the explanation.
