### ISSUE TITLE
ValidationReporter Issues

### ISSUE THREAD

**Issue by DavidSteinJr** [varigence/BimlPit#68]
I'm currently using the latest version of BimlStudio 2018. 

I've noticed the following issues when attempting to use the ValidationReporter: 

1. It appears that using any Severity other than Error is pointless in an Executed Biml Script. Nothing would show up in the Build Output, right? 
2. When ValidationReporter.Report (of any severity) is used in a Biml Script that is executed, the execution throws an  "object reference not set to an instance of an object" error.
3. When a script is viewed in the BimlScript Designer, only Errors show in the window directly below, even though there are tabs for Warnings and Messages. Shouldn't Warnings show in this window? 

Sample code is as follows:
```
<#@ template language="C#" tier="10"#>
<Biml xmlns="http://schemas.varigence.com/biml.xsd">
	<Packages>
		<Package Name="ValidationReporterTest" PackageSubpath="ValidationReporterTest" ProtectionLevel="EncryptSensitiveWithUserKey">
<#
	//ValidationReporter.Report(Severity.Message , "Umm... there's a problem.");
	//ValidationReporter.Report(Severity.Warning , "Umm... there's a problem.");
	ValidationReporter.Report(Severity.Error , "Umm... there's a problem.");	
#>			
        </Package>
    </Packages>
</Biml>

```

**Comment by scottcurrie** [comment]
1) Nothing will show up in the build output for executed BimlScripts. For that to happen, you would need to use live BimlScripts or CallBimlScript. Once a BimlScript is executed, the only artifact created is the expanded Biml. This aspect is by design.

2) This has been fixed for Execute BimlScript in the upcoming release.

3) Warnings and notifications are buttons you can click to toggle showing them.
